Repository TeamCARDNA/CardnaAndroid, pull requests merged in 2022-01, with the labels that each got.

#6 Feature/1 init setting
  app/build.gradle
  app/src/main/java/org/cardna/MainActivity.kt
  app/src/main/java/org/cardna/ui/Temp.kt
  app/src/main/java/org/cardna/ui/cardpack/CardPackFragment.kt
  app/src/main/java/org/cardna/ui/insight/InsightFragment.kt
  app/src/main/java/org/cardna/ui/maincard/MainCardFragment.kt
  app/src/main/java/org/cardna/ui/mypage/MyPageFragment.kt
  app/src/main/java/org/cardna/util/Temp.kt
  app/src/main/res/drawable-v24/selector_main_cardpack.xml
  app/src/main/res/drawable/ic_bottomnavigation_person.xml
  app/src/main/res/drawable/ic_bottomnavigation_smailing.xml
  app/src/main/res/drawable/ic_bottomnavigation_tray.xml
  app/src/main/res/drawable/ic_bottomnavigation_union.xml
  app/src/main/res/drawable/ic_main_cardpack_checked.xml
  app/src/main/res/drawable/ic_main_cardpack_unchecked.xml
  app/src/main/res/drawable/ic_main_insight_checked.xml
  app/src/main/res/drawable/ic_main_insight_unchecked.xml
  app/src/main/res/drawable/ic_main_maincard_checked.xml
  app/src/main/res/drawable/ic_main_maincard_unchecked.xml
  app/src/main/res/drawable/ic_main_mypage_checked.xml
  app/src/main/res/drawable/ic_main_mypage_unchecked.xml
  app/src/main/res/drawable/selector_main_insight.xml
  app/src/main/res/drawable/selector_main_maincard.xml
  app/src/main/res/drawable/selector_main_mypage.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_card_pack.xml
  app/src/main/res/layout/fragment_insight.xml
  app/src/main/res/layout/fragment_main_card.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/menu/menu_main.xml
  app/src/main/res/navigation/main_nav.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values-land/dimens.xml
  app/src/main/res/values-w1240dp/dimens.xml
  app/src/main/res/values-w600dp/dimens.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Dabin, review request

#14 [FEAT] : #13 - DetailCardActivity xml 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cardna/base/baseutil/BaseViewUtil.kt
  app/src/main/java/org/cardna/ui/maincard/DetailCardActivity.kt
  app/src/main/res/drawable/ic_arrow_left.xml
  app/src/main/res/drawable/ic_option.xml
  app/src/main/res/drawable/ic_share.xml
  app/src/main/res/drawable/rectangle_black_radius_2.xml
  app/src/main/res/drawable/rectangle_left_right_null_radius_2.xml
  app/src/main/res/drawable/rectangle_right_null_black_radius_2.xml
  app/src/main/res/layout/activity_detail_card.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/style.xml
Labels: Jongchan, review request

#16 Feature/8 cardpack fragment
  app/src/main/java/org/cardna/MainActivity.kt
  app/src/main/java/org/cardna/base/baseutil/BaseViewUtil.kt
  app/src/main/java/org/cardna/data/remote/model/Temp.kt
  app/src/main/java/org/cardna/data/remote/model/cardpack/ResponseCardPackMeData.kt
  app/src/main/java/org/cardna/data/remote/model/cardpack/ResponseCardPackYouData.kt
  app/src/main/java/org/cardna/ui/cardpack/CardMeFragment.kt
  app/src/main/java/org/cardna/ui/cardpack/CardPackFragment.kt
  app/src/main/java/org/cardna/ui/cardpack/CardYouFragment.kt
  app/src/main/java/org/cardna/ui/cardpack/adapter/CardPackMeRecyclerViewAdapter.kt
  app/src/main/java/org/cardna/ui/cardpack/adapter/CardPackTabLayoutAdapter.kt
  app/src/main/java/org/cardna/ui/cardpack/adapter/CardPackYouRecyclerViewAdapter.kt
  app/src/main/java/org/cardna/ui/insight/InsightFragment.kt
  app/src/main/java/org/cardna/ui/maincard/MainCardFragment.kt
  app/src/main/java/org/cardna/ui/mypage/MyPageFragment.kt
  app/src/main/res/drawable/background_rv_border.xml
  app/src/main/res/drawable/background_rv_iv_border.xml
  app/src/main/res/drawable/dummy_img_cardpack_1.9.png
  app/src/main/res/drawable/ic_cardme_active.xml
  app/src/main/res/drawable/ic_cardme_inactive.xml
  app/src/main/res/drawable/ic_cardpack_add_card.xml
  app/src/main/res/drawable/ic_cardyou_active.xml
  app/src/main/res/drawable/ic_cardyou_inactive.xml
  app/src/main/res/drawable/selector_cardpack_tab_cardme.xml
  app/src/main/res/drawable/selector_cardpack_tab_cardme_line.xml
  app/src/main/res/drawable/selector_cardpack_tab_cardme_text.xml
  app/src/main/res/drawable/selector_cardpack_tab_cardyou.xml
  app/src/main/res/drawable/selector_cardpack_tab_cardyou_line.xml
  app/src/main/res/drawable/selector_cardpack_tab_cardyou_text.xml
  app/src/main/res/layout/cardpack_custom_tablayout.xml
  app/src/main/res/layout/fragment_card_me.xml
  app/src/main/res/layout/fragment_card_pack.xml
  app/src/main/res/layout/fragment_card_you.xml
  app/src/main/res/layout/item_cardpack_cardme.xml
  app/src/main/res/layout/item_cardpack_cardyou.xml
  app/src/main/res/values/styles.xml
Labels: Minwoo, In Progress

#11 Feature/7 create card view
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cardna/ui/cardpack/CardCreateActivity.kt
  app/src/main/res/drawable/ic_item_group.xml
  app/src/main/res/drawable/rectangle_main_green_radius_10.xml
  app/src/main/res/drawable/rectangle_text_hint_radius_10.xml
  app/src/main/res/layout/activity_card_create.xml
  app/src/main/res/layout/fragment_main_card.xml
  app/src/main/res/navigation/main_nav.xml
  app/src/main/res/values/colors.xml
Labels: Minwoo, Jongchan, In Progress

#20 Feature/18 mypage activity
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cardna/data/remote/model/cardpack/ResponseCardPackMeData.kt
  app/src/main/java/org/cardna/data/remote/model/mypage/ResponseMyPageFriendData.kt
  app/src/main/java/org/cardna/ui/cardpack/CardMeFragment.kt
  app/src/main/java/org/cardna/ui/cardpack/CardYouFragment.kt
  app/src/main/java/org/cardna/ui/cardpack/adapter/CardPackMeRecyclerViewAdapter.kt
  app/src/main/java/org/cardna/ui/maincard/MainCardFragment.kt
  app/src/main/java/org/cardna/ui/mypage/MyPageFragment.kt
  app/src/main/java/org/cardna/ui/mypage/MyPageScrollView.kt
  app/src/main/java/org/cardna/ui/mypage/OtherWriteActivity.kt
  app/src/main/java/org/cardna/ui/mypage/SearchEmailActivity.kt
  app/src/main/java/org/cardna/ui/mypage/SettingActivity.kt
  app/src/main/java/org/cardna/ui/mypage/adapter/MyPageFriendAdapter.kt
  app/src/main/java/org/cardna/util/SpacesItemDecoration.kt
  app/src/main/java/org/cardna/util/ViewExt.kt
  app/src/main/res/drawable-v24/img_friend_image.9.png
  app/src/main/res/drawable-v24/img_my_profile.9.png
  app/src/main/res/drawable/ic_goto_others_wrote.xml
  app/src/main/res/drawable/ic_goto_search_email.xml
  app/src/main/res/drawable/ic_magnifier.xml
  app/src/main/res/drawable/ic_setting.xml
  app/src/main/res/drawable/rectangle_dark_grey_radius_10.xml
  app/src/main/res/drawable/rectangle_grey_radius_10.xml
  app/src/main/res/layout/activity_other_write.xml
  app/src/main/res/layout/activity_search_email.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_cardpack_cardme.xml
  app/src/main/res/layout/item_mypage_friend.xml
Labels: Dabin, Complete

#22 Feature/21 emailsearch activity
  app/src/main/java/org/cardna/ui/maincard/RepresentCardEditActivity.kt
  app/src/main/java/org/cardna/ui/maincard/RepresentCardEditBottomDialogFragment.kt
  app/src/main/java/org/cardna/ui/mypage/MyPageFragment.kt
  app/src/main/java/org/cardna/ui/mypage/SearchEmailActivity.kt
  app/src/main/res/drawable-v24/img_searchemail_friend_image.9.png
  app/src/main/res/drawable/ic_searchemail_add_friend.xml
  app/src/main/res/drawable/rectangle_null_white_1_5_radius_16.xml
  app/src/main/res/drawable/selector_searchemail_add_friend.xml
  app/src/main/res/layout/activity_search_email.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_mypage_friend.xml
  app/src/main/res/values/styles.xml
Labels: Dabin, review request

#28 Feature/17 cardpack bottomsheet
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cardna/MainActivity.kt
  app/src/main/java/org/cardna/ui/cardpack/BottomDialogCardFragment.kt
  app/src/main/java/org/cardna/ui/cardpack/BottomDialogImageFragment.kt
  app/src/main/java/org/cardna/ui/cardpack/CardCreateActivity.kt
  app/src/main/java/org/cardna/ui/cardpack/CardCreateCompleteDialog.kt
  app/src/main/java/org/cardna/ui/cardpack/CardPackFragment.kt
  app/src/main/java/org/cardna/ui/maincard/MainCardFragment.kt
  app/src/main/res/drawable/background_bs_border.xml
  app/src/main/res/drawable/background_cardme.xml
  app/src/main/res/drawable/background_cardyou.xml
  app/src/main/res/drawable/cursor_color.xml
  app/src/main/res/drawable/dummy_ic_card_complete.9.png
  app/src/main/res/drawable/edittext_bottom_line.xml
  app/src/main/res/drawable/ic_bottomsheet_cardme.xml
  app/src/main/res/drawable/ic_bottomsheet_cardyou.xml
  app/src/main/res/drawable/ic_card_create_complete_0.png
  app/src/main/res/drawable/ic_cardpack_gallery.xml
  app/src/main/res/drawable/ic_symbol_cardme_0.9.png
  app/src/main/res/drawable/ic_symbol_cardme_1.9.png
  app/src/main/res/drawable/ic_symbol_cardme_2.9.png
  app/src/main/res/drawable/ic_symbol_cardme_3.9.png
  app/src/main/res/drawable/ic_symbol_cardme_4.9.png
  app/src/main/res/drawable/ic_symbol_cardyou_0.9.png
  app/src/main/res/drawable/ic_symbol_cardyou_1.9.png
  app/src/main/res/drawable/ic_symbol_cardyou_2.9.png
  app/src/main/res/drawable/ic_symbol_cardyou_3.9.png
  app/src/main/res/drawable/ic_symbol_cardyou_4.9.png
  app/src/main/res/drawable/ic_symbol_selected_0.xml
  app/src/main/res/drawable/ic_symbol_selected_1.xml
  app/src/main/res/drawable/ic_symbol_selected_2.xml
  app/src/main/res/drawable/ic_symbol_selected_3.xml
  app/src/main/res/drawable/ic_symbol_selected_4.xml
  app/src/main/res/drawable/ic_symbol_unselected_0.xml
  app/src/main/res/drawable/ic_symbol_unselected_1.xml
  app/src/main/res/drawable/ic_symbol_unselected_2.xml
  app/src/main/res/drawable/ic_symbol_unselected_3.xml
  app/src/main/res/drawable/ic_symbol_unselected_4.xml
  app/src/main/res/drawable/rectangle_text_hint_radius_10.xml
  app/src/main/res/drawable/selector_cardcreate_symbol_0.xml
  app/src/main/res/drawable/selector_cardcreate_symbol_1.xml
  app/src/main/res/drawable/selector_cardcreate_symbol_2.xml
  app/src/main/res/drawable/selector_cardcreate_symbol_3.xml
  app/src/main/res/drawable/selector_cardcreate_symbol_4.xml
  app/src/main/res/layout/activity_card_create.xml
  app/src/main/res/layout/fragment_bottom_dialog_card.xml
  app/src/main/res/layout/fragment_bottom_dialog_image.xml
  app/src/main/res/layout/fragment_card_me.xml
  app/src/main/res/layout/item_cardcreate_complete_dialog.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: Minwoo, Complete

#32 Feature/21 emailsearch activity
  app/src/main/java/org/cardna/ui/mypage/SearchEmailActivity.kt
  app/src/main/res/drawable/ic_vector_990__stroke_.xml
  app/src/main/res/drawable/rectangle_null_white_1_5_radius_16.xml
  app/src/main/res/layout/activity_search_email.xml
Labels: Dabin, In Progress

#33 # 18 "[REFACTOR] : SettingActivity 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cardna/ui/mypage/SettingActivity.kt
  app/src/main/res/layout/activity_setting.xml
Labels: Jongchan, In Progress

#41 Feature/40 otherwrite activity
  app/src/main/java/org/cardna/data/remote/model/cardpack/ResponseOtherWriterData.kt
  app/src/main/java/org/cardna/ui/cardpack/adapter/OtherWriteRecyclerViewAdapter.kt
  app/src/main/java/org/cardna/ui/mypage/OtherWriteActivity.kt
  app/src/main/res/drawable-v24/img_insight_buildarea.9.png
  app/src/main/res/img_blindarea/img_insight_buildarea.png
  app/src/main/res/img_openarea/img_insight_openarea.png
  app/src/main/res/layout/activity_other_write.xml
  app/src/main/res/layout/item_otherwrite.xml
Labels: Dabin, Complete

#43 Feature/41 alarm activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cardna/ui/maincard/AlarmActivity.kt
  app/src/main/java/org/cardna/ui/maincard/MainCardFragment.kt
  app/src/main/java/org/cardna/ui/maincard/adapter/AlarmRecyclerViewAdapter.kt
  app/src/main/java/org/cardna/ui/mypage/OtherWriteActivity.kt
  app/src/main/java/org/cardna/ui/mypage/adapter/OtherWriteRecyclerViewAdapter.kt
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/item_alarm.xml
Labels: Dabin, Complete

#46 Feat/29 access gallery
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cardna/ui/cardpack/CardCreateActivity.kt
  app/src/main/java/org/cardna/ui/cardpack/CardCreateCompleteActivity.kt
  app/src/main/java/org/cardna/ui/cardpack/CardCreateCompleteDialog.kt
  app/src/main/res/layout/activity_card_create.xml
  app/src/main/res/layout/activity_card_create_complete.xml
  app/src/main/res/layout/activity_other_card_write.xml
  app/src/main/res/layout/fragment_card_me.xml
  app/src/main/res/layout/fragment_card_you.xml
  app/src/main/res/layout/item_othercardcreate_complete_dialog.xml
  app/src/main/res/raw/lottie_cardme.json
  app/src/main/res/raw/lottie_cardyou.json
  app/src/main/res/values/styles.xml
Labels: Complete

#53 Feat/29 access gallery
  app/src/main/java/org/cardna/ui/cardpack/CardCreateActivity.kt
  app/src/main/java/org/cardna/ui/cardpack/CardCreateCompleteActivity.kt
  app/src/main/java/org/cardna/ui/cardpack/CardPackFragment.kt
  app/src/main/java/org/cardna/ui/mypage/MyPageFragment.kt
  app/src/main/java/org/cardna/ui/mypage/OtherCardCreateActivity.kt
  app/src/main/java/org/cardna/ui/mypage/OtherCardWriteActivity.kt
  app/src/main/java/org/cardna/ui/mypage/OtherWriteActivity.kt
  app/src/main/res/drawable/ic_symbol_cardme_2.9.png
  app/src/main/res/drawable/ic_symbol_cardme_3.9.png
  app/src/main/res/drawable/ic_symbol_cardme_4.9.png
  app/src/main/res/drawable/rectangle_left_right_main_purple_radius_2.xml
  app/src/main/res/layout/fragment_blind_area.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_open_area.xml
  app/src/main/res/layout/item_mypage_friend.xml
Labels: Complete

#52 Feature/45 maincard layout
  app/src/main/java/org/cardna/data/remote/model/detail/ResponseDetailData.kt
  app/src/main/java/org/cardna/data/remote/model/maincard/MainCardListData.kt
  app/src/main/java/org/cardna/ui/cardpack/CardCreateActivity.kt
  app/src/main/java/org/cardna/ui/maincard/DetailCardMeActivity.kt
  app/src/main/java/org/cardna/ui/maincard/MainCardFragment.kt
  app/src/main/java/org/cardna/ui/maincard/adapter/MainCardAdapter.kt
  app/src/main/res/drawable/ic_detail_3dot.xml
  app/src/main/res/drawable/ic_mypage_friend_checked.xml
  app/src/main/res/drawable/ic_mypage_friend_unchecked.xml
  app/src/main/res/drawable/ic_mypage_write.xml
  app/src/main/res/drawable/rectangle_left_right_main_purple.xml
  app/src/main/res/drawable/rectangle_main_purple.xml
  app/src/main/res/drawable/rectangle_maincard_gradient_radius_45.xml
  app/src/main/res/layout/activity_detail_card.xml
  app/src/main/res/layout/fragment_main_card.xml
Labels: In Progress

#60 Feat/29 access gallery
  app/src/main/res/drawable/ic_gallery.xml
  app/src/main/res/drawable/ic_like_selected.9.png
  app/src/main/res/drawable/ic_like_unselected.9.png
  app/src/main/res/drawable/selector_detailcard_like.xml
  app/src/main/res/layout/activity_detail_card.xml
  app/src/main/res/layout/activity_detail_card_you.xml
  app/src/main/res/layout/item_otherwrite.xml
Labels: Complete

#59 Feature/56 init network setting
  app/src/main/java/org/cardna/ui/cardpack/CardMeFragment.kt
  app/src/main/java/org/cardna/ui/cardpack/CardYouFragment.kt
  app/src/main/java/org/cardna/ui/cardpack/adapter/CardPackMeRecyclerViewAdapter.kt
  app/src/main/java/org/cardna/ui/cardpack/adapter/CardPackYouRecyclerViewAdapter.kt
  app/src/main/java/org/cardna/ui/maincard/DetailActivity.kt
  app/src/main/res/layout/activity_detail.xml
Labels: Dabin

#62 Feature/56 init network setting
  app/src/main/java/org/cardna/data/remote/api/AuthService.kt
  app/src/main/java/org/cardna/data/remote/api/CardService.kt
  app/src/main/java/org/cardna/data/remote/api/FriendService.kt
  app/src/main/java/org/cardna/data/remote/api/InsightService.kt
  app/src/main/java/org/cardna/data/remote/api/LikeService.kt
  app/src/main/java/org/cardna/data/remote/api/MypageService.kt
  app/src/main/java/org/cardna/ui/cardpack/CardMeFragment.kt
  app/src/main/java/org/cardna/ui/cardpack/CardYouFragment.kt
Labels: Dabin

#68 Feature/61 network setting
  app/src/main/java/org/cardna/data/remote/model/cardpack/RequestCreateCardMeData.kt
  app/src/main/java/org/cardna/data/remote/model/cardpack/ResponseCardAllData.kt
  app/src/main/java/org/cardna/data/remote/model/cardpack/ResponseCardDetailData.kt
  app/src/main/java/org/cardna/data/remote/model/cardpack/ResponseCardMeData.kt
  app/src/main/java/org/cardna/data/remote/model/cardpack/ResponseCardYouData.kt
  app/src/main/java/org/cardna/data/remote/model/cardpack/ResponseCreateCardMeData.kt
  app/src/main/java/org/cardna/data/remote/model/maincard/RequestMainCardEditData.kt
  app/src/main/java/org/cardna/data/remote/model/maincard/ResponseDeleteCardData.kt
  app/src/main/java/org/cardna/data/remote/model/maincard/ResponseMainCardData.kt
  app/src/main/java/org/cardna/data/remote/model/maincard/ResponseMainCardEditData.kt
  app/src/main/java/org/cardna/data/remote/model/mypage/Data.kt
  app/src/main/java/org/cardna/data/remote/model/mypage/RequestCreateCardYouData.kt
  app/src/main/java/org/cardna/data/remote/model/mypage/ResponseAddOrRemoveCardYouData.kt
  app/src/main/java/org/cardna/data/remote/model/mypage/ResponseCheckCardYouStorageData.kt
  app/src/main/java/org/cardna/data/remote/model/mypage/ResponseCreateCardYouData.kt
Labels: Minwoo, Complete

#72 Feature/67 maincard network
  app/build.gradle
  app/src/main/java/org/cardna/data/remote/api/ApiService.kt
  app/src/main/java/org/cardna/data/remote/api/CardService.kt
  app/src/main/java/org/cardna/data/remote/model/maincard/Data.kt
  app/src/main/java/org/cardna/data/remote/model/maincard/MainCard.kt
  app/src/main/java/org/cardna/data/remote/model/maincard/ResponseMainCardData.kt
  app/src/main/java/org/cardna/data/remote/model/maincard/Test.kt
  app/src/main/java/org/cardna/ui/maincard/MainCardFragment.kt
  app/src/main/java/org/cardna/ui/maincard/ResponseWrapperData.kt
  app/src/main/java/org/cardna/ui/maincard/adapter/MainCardAdapter.kt
Labels: Complete

#73 Feature/61 network setting
  app/src/main/java/org/cardna/data/remote/api/CardService.kt
  app/src/main/java/org/cardna/data/remote/model/mypage/ResponseCardYouBoxData.kt
  app/src/main/java/org/cardna/ui/maincard/DetailCardMeActivity.kt
  app/src/main/java/org/cardna/ui/maincard/DetailCardYouActivity.kt
  app/src/main/res/drawable/ic_like_selected.9.png
  app/src/main/res/drawable/ic_like_selected.xml
  app/src/main/res/drawable/ic_like_unselected.9.png
  app/src/main/res/drawable/ic_like_unselected.xml
  app/src/main/res/drawable/ic_minous_btn.xml
  app/src/main/res/layout/activity_detail_card_me.xml
  app/src/main/res/layout/activity_detail_card_you.xml
Labels: Minwoo, Complete

#80 Feature/67 maincard network
  app/src/main/java/org/cardna/data/remote/api/CardService.kt
  app/src/main/java/org/cardna/data/remote/api/FriendService.kt
  app/src/main/java/org/cardna/ui/maincard/DetailCardMeActivity.kt
  app/src/main/res/layout/fragment_main_card.xml
Labels: Dabin, Complete

#84 Feature/61 network setting
  app/src/main/java/org/cardna/data/remote/api/CardService.kt
  app/src/main/java/org/cardna/data/remote/model/cardpack/RequestCreateCardMeData.kt
  app/src/main/java/org/cardna/data/remote/model/cardpack/ResponseCardMeData.kt
  app/src/main/java/org/cardna/ui/cardpack/BottomDialogImageFragment.kt
  app/src/main/java/org/cardna/ui/cardpack/CardCreateActivity.kt
  app/src/main/java/org/cardna/ui/cardpack/CardCreateCompleteActivity.kt
  app/src/main/java/org/cardna/ui/cardpack/CardMeFragment.kt
  app/src/main/java/org/cardna/ui/cardpack/CardPackFragment.kt
  app/src/main/java/org/cardna/ui/cardpack/adapter/CardPackMeRecyclerViewAdapter.kt
  app/src/main/java/org/cardna/ui/insight/BlindAreaFragment.kt
  app/src/main/java/org/cardna/ui/insight/InsightFragment.kt
  app/src/main/java/org/cardna/ui/mypage/BottomDialogOtherImageFragment.kt
  app/src/main/java/org/cardna/ui/mypage/MyPageFragment.kt
  app/src/main/java/org/cardna/ui/mypage/OtherCardCreateActivity.kt
  app/src/main/java/org/cardna/ui/mypage/OtherCardWriteActivity.kt
  app/src/main/java/org/cardna/ui/representcardedit/RepresentCardEditBottomDialogFragment.kt
  app/src/main/res/drawable/rectangle_left_right_main_purple_radius_2.xml
  app/src/main/res/layout/activity_card_create.xml
  app/src/main/res/layout/activity_card_create_complete.xml
  app/src/main/res/layout/activity_other_card_create_complete.xml
  app/src/main/res/layout/fragment_blind_area.xml
  app/src/main/res/layout/fragment_insight.xml
  app/src/main/res/layout/fragment_open_area.xml
  app/src/main/res/layout/item_cardpack_cardme.xml
  app/src/main/res/layout/item_main_card_view.xml
Labels: Minwoo, Complete

#88 Feature/61 network setting
  app/src/main/java/org/cardna/data/remote/api/CardService.kt
  app/src/main/java/org/cardna/data/remote/model/cardpack/ResponseCardMeData.kt
  app/src/main/java/org/cardna/data/remote/model/cardpack/ResponseCardYouData.kt
  app/src/main/java/org/cardna/ui/cardpack/BottomDialogImageFragment.kt
  app/src/main/java/org/cardna/ui/cardpack/CardCreateActivity.kt
  app/src/main/java/org/cardna/ui/cardpack/CardCreateCompleteActivity.kt
  app/src/main/java/org/cardna/ui/cardpack/CardMeFragment.kt
  app/src/main/java/org/cardna/ui/cardpack/CardPackFragment.kt
  app/src/main/java/org/cardna/ui/cardpack/adapter/CardPackMeRecyclerViewAdapter.kt
  app/src/main/java/org/cardna/ui/maincard/DetailActivity.kt
  app/src/main/java/org/cardna/ui/maincard/adapter/RepresentBottomSheetCardMeAdapter.kt
  app/src/main/java/org/cardna/ui/maincard/adapter/RepresentBottomSheetCardYouAdapter.kt
  app/src/main/java/org/cardna/ui/representcardedit/RepresentCardEditBottomDialogFragment.kt
  app/src/main/res/drawable/ic_symbol_cardyou_2.9.png
  app/src/main/res/drawable/ic_symbol_cardyou_3.9.png
  app/src/main/res/drawable/ic_symbol_cardyou_4.9.png
  app/src/main/res/layout/activity_card_create_complete.xml
  app/src/main/res/layout/activity_detail.xml
Labels: Complete

#96 Feature/90 card create network
  app/src/main/java/org/cardna/data/remote/api/CardService.kt
  app/src/main/java/org/cardna/data/remote/model/mypage/RequestCreateCardYouData.kt
  app/src/main/java/org/cardna/data/remote/model/mypage/ResponseCreateCardYouData.kt
  app/src/main/java/org/cardna/ui/cardpack/BottomDialogImageFragment.kt
  app/src/main/java/org/cardna/ui/cardpack/CardCreateActivity.kt
  app/src/main/java/org/cardna/ui/cardpack/CardCreateCompleteActivity.kt
  app/src/main/java/org/cardna/ui/cardpack/CardPackFragment.kt
  app/src/main/java/org/cardna/ui/maincard/AlarmActivity.kt
  app/src/main/java/org/cardna/ui/maincard/MainCardFragment.kt
  app/src/main/java/org/cardna/ui/mypage/BottomDialogOtherImageFragment.kt
  app/src/main/java/org/cardna/ui/mypage/OtherCardCreateActivity.kt
  app/src/main/java/org/cardna/ui/mypage/OtherCardWriteActivity.kt
  app/src/main/res/layout/activity_other_card_create.xml
  app/src/main/res/layout/activity_other_card_create_complete.xml
  app/src/main/res/layout/activity_other_card_write.xml
Labels: Complete

#101 Feature/90 card create network
  app/src/main/java/org/cardna/data/remote/api/ApiService.kt
  app/src/main/java/org/cardna/ui/cardpack/CardCreateActivity.kt
  app/src/main/java/org/cardna/ui/cardpack/CardCreateCompleteActivity.kt
  app/src/main/java/org/cardna/ui/maincard/DetailActivity.kt
  app/src/main/java/org/cardna/ui/mypage/OtherCardCreateActivity.kt
  app/src/main/java/org/cardna/ui/mypage/OtherCardCreateCompleteActivity.kt
  app/src/main/java/org/cardna/ui/mypage/OtherCardWriteActivity.kt
  app/src/main/res/layout/activity_card_create.xml
  app/src/main/res/layout/activity_other_card_create.xml
  app/src/main/res/layout/activity_other_card_create_complete.xml
  app/src/main/res/layout/activity_other_card_write.xml
  app/src/main/res/layout/item_otherwrite.xml
Labels: Complete

#104 [ADD] #103 - SplashActivity sample image setting
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/cardna/SplashActivity.kt
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/raw/lottie_splash_sample.json
Labels: Dabin, In Progress

#108 Feature/90 card create network
  app/src/main/java/org/cardna/ui/cardpack/CardCreateActivity.kt
  app/src/main/java/org/cardna/ui/cardpack/CardMeFragment.kt
  app/src/main/java/org/cardna/ui/cardpack/CardYouFragment.kt
  app/src/main/java/org/cardna/ui/maincard/DetailCardMeActivity.kt
  app/src/main/java/org/cardna/ui/mypage/OtherWriteActivity.kt
  app/src/main/java/org/cardna/util/SpacesItemDecoration.kt
  app/src/main/res/drawable/background_card_black_line.xml
  app/src/main/res/drawable/background_round.xml
  app/src/main/res/drawable/background_rv_iv_border.xml
  app/src/main/res/layout/activity_card_create.xml
  app/src/main/res/layout/activity_card_create_complete.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_detail_card_me.xml
Labels: Complete

#111 Feature/90 card create network
  app/src/main/java/org/cardna/data/remote/api/ApiService.kt
  app/src/main/java/org/cardna/data/remote/api/CardService.kt
  app/src/main/java/org/cardna/ui/cardpack/CardCreateActivity.kt
  app/src/main/java/org/cardna/ui/cardpack/CardCreateCompleteActivity.kt
  app/src/main/java/org/cardna/ui/maincard/AlarmActivity.kt
  app/src/main/java/org/cardna/ui/maincard/DetailActivity.kt
  app/src/main/java/org/cardna/ui/maincard/DetailCardMeActivity.kt
  app/src/main/java/org/cardna/ui/mypage/OtherCardCreateActivity.kt
  app/src/main/java/org/cardna/ui/mypage/OtherCardWriteActivity.kt
  app/src/main/res/layout/activity_other_card_write.xml
Labels: Minwoo

#115 [FEAT] #90 - createCardMe createCardYou network complete
  app/src/main/java/org/cardna/data/remote/api/ApiService.kt
  app/src/main/java/org/cardna/ui/cardpack/CardCreateActivity.kt
  app/src/main/java/org/cardna/ui/maincard/DetailActivity.kt
  app/src/main/java/org/cardna/ui/mypage/OtherCardWriteActivity.kt
Labels: Complete

#123 Feature/90 card create network
  app/src/main/java/org/cardna/ui/mypage/MyPageFragment.kt
Labels: Complete

#127 Feature/90 card create network
  app/src/main/java/org/cardna/ui/mypage/MyPageFragment.kt
  app/src/main/res/layout/fragment_blind_area.xml
  app/src/main/res/layout/fragment_open_area.xml
  app/src/main/res/layout/item_cardpack_cardme.xml
  app/src/main/res/layout/item_cardpack_cardyou.xml
  app/src/main/res/layout/item_represent_edit_card.xml
Labels: Complete

#132 Feature/90 card create network
  app/src/main/java/org/cardna/ui/representcardedit/RepresentCardEditBottomDialogFragment.kt
  app/src/main/res/layout/fragment_main_card.xml
  app/src/main/res/layout/fragment_represent_card_edit_bottom_dialog.xml
  app/src/main/res/layout/item_represent_card_me.xml
  app/src/main/res/layout/item_represent_card_you.xml
  app/src/main/res/values/strings.xml
Labels: Complete
